### ISSUE TITLE
Link to Wiki doesn't work

### ISSUE THREAD

**Issue by philsward** [backdrop-contrib/token_help#1]
The link to https://github.com/backdrop-contrib/token_help/wiki/Documentation doesn't seem to work as advertised.

It redirects back to https://github.com/backdrop-contrib/token_help/

**Comment by bugfolder** [comment]
This turns out to be a Github oddity: if one is logged into Github and the wiki is empty, it takes you the empty Wiki page:

![wiki](https://user-images.githubusercontent.com/29214084/141380897-71c26724-a51e-437b-a2e3-25854a1325ac.jpg)

But if you're not logged into Github, then it throws you back to the main project page, as you report.

The solution is one of

* Don't include any link to the wiki if it's empty. (But then no one will know they can add to the wiki just by logging in.)
* Keep the link, but note that you have to be logged in to see it.

Unfortunately, there's a ton of module README pages that (like this one) include a similar link to the Wiki, so this issue is pretty widespread.

I think that for now I'll just remove the link in the README entirely since the Wiki is empty.

**Comment by philsward** [comment]
Sounds like a plan.

**Comment by philsward** [comment]
Just as a quick update, I don't think it matters if you're logged in or not. If the wiki page doesn't exist, anyone who doesn't have access to edit the wiki is redirected.

I realized after the fact that I was indeed logged in and it still redirected.

For what it's worth.

**Comment by bugfolder** [comment]
Interesting, good to know. So perhaps it doesn't redirect only if one has admin access to the repository.

**Comment by philsward** [comment]
@bugfolder that's my guess.
